version: '2'
services:
  sbt:
    build: ./sbt
    image: sbt
    ports:
    - "9000:9000"
    volumes:
    - ../:/root
    links:
    - dynamodb
    stdin_open: true
    environment:
        # Mocked Aws SDK Credentials for Local DynamoDB
        # http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Credentials_from_Environment_Variables
        - AWS_ACCESS_KEY_ID=123
        - AWS_SECRET_ACCESS_KEY=abc
        - LOCAL_DYNAMO_DB=true
  dynamodb:
    build: ./dynamodb
    image: dynamodb
    ports:
    - 8000:8000
    environment:
        - TABLE=${DYNAMODB_TABLE}
